remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme

title: Sanika Naik
description: Software Developer with expertise in ERP and HRM systems, proficient in C#, ASP.NET MVC, and SQL Server. Building enterprise solutions that streamline business operations
